FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY src/Estoque/OficinaMecanica.Estoque.Domain/OficinaMecanica.Estoque.Domain.csproj src/Estoque/OficinaMecanica.Estoque.Domain/
COPY src/Estoque/OficinaMecanica.Estoque.Application/OficinaMecanica.Estoque.Application.csproj src/Estoque/OficinaMecanica.Estoque.Application/
COPY src/Estoque/OficinaMecanica.Estoque.Infrastructure/OficinaMecanica.Estoque.Infrastructure.csproj src/Estoque/OficinaMecanica.Estoque.Infrastructure/
COPY src/Estoque/OficinaMecanica.Estoque.API/OficinaMecanica.Estoque.API.csproj src/Estoque/OficinaMecanica.Estoque.API/

RUN dotnet restore src/Estoque/OficinaMecanica.Estoque.API/OficinaMecanica.Estoque.API.csproj

COPY src/ src/

RUN dotnet publish src/Estoque/OficinaMecanica.Estoque.API/OficinaMecanica.Estoque.API.csproj \
    -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080
ENTRYPOINT ["dotnet", "OficinaMecanica.Estoque.API.dll"]
