version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: techchallenge-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=techchallengedb;Username=postgres;Password=postgres123
      - Jwt__Key=TechChallenge_SuperSecretKey_2024_Oficina_Mecanica!
      - Jwt__Issuer=TechChallenge.API
      - Jwt__Audience=TechChallenge.Client
      - Jwt__ExpiracaoMinutos=60
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: techchallenge-db
    environment:
      POSTGRES_DB: techchallengedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
