apiVersion: v1
kind: ConfigMap
metadata:
  name: atendimento-config
  namespace: oficina-mecanica
data:
  ASPNETCORE_ENVIRONMENT: Production
  ASPNETCORE_URLS: http://+:8080
  RabbitMq__Enabled: "true"
  RabbitMq__Host: rabbitmq-svc
  EstoqueHttp__Enabled: "true"
  EstoqueServiceUrl: http://estoque-svc
  Jwt__Issuer: oficina-atendimento
  Jwt__Audience: oficina-atendimento-api
  Jwt__ExpiracaoMinutos: "60"
  Smtp__Host: smtp.gmail.com
  Smtp__Port: "587"
  Smtp__From: "Oficina Mecanica <oficina@exemplo.com>"
