apiVersion: v1
kind: Secret
metadata:
  name: atendimento-secrets
  namespace: oficina-mecanica
type: Opaque
data:
  Jwt__Key: cGxhY2Vob2xkZXItZGV2LWtleS1taW5pbXVtLTMyLWNoYXJzLWhlcmUh
  ConnectionStrings__DefaultConnection: SG9zdD1wb3N0Z3Jlcy1zdmM7UG9ydD01NDMyO0RhdGFiYXNlPW9maWNpbmFfYXRlbmRpbWVudG87VXNlcm5hbWU9cG9zdGdyZXM7UGFzc3dvcmQ9cG9zdGdyZXM=
  Smtp__Password: ""
