apiVersion: v1
kind: Secret
metadata:
  name: estoque-secrets
  namespace: oficina-mecanica
type: Opaque
data:
  ConnectionStrings__DefaultConnection: SG9zdD1wb3N0Z3Jlcy1zdmM7UG9ydD01NDMyO0RhdGFiYXNlPW9maWNpbmFfZXN0b3F1ZTtVc2VybmFtZT1wb3N0Z3JlcztQYXNzd29yZD1wb3N0Z3Jlcw==
